export const DASHBOARD_SSE_WORKER = {
  RETRY_INTERVAL: 1000,
  MAXIMUM_RETRY_TIME: 30000,
  MAXIMUM_RETRY_COUNT: 5,
  CONNECTION_STATUS: {
    PREPARE: 0,
    CONNECTING: 1,
    CONNECTED: 2,
    DISCONNECTED: 3,
  } as const,
} as const;

export const DASHBOARD_SSE_SHARED_WORKER = {
  PING_INTERVAL: 30 * 1000,
  MAXIMUM_PING_TIMEOUT: 3 * 30 * 1000,
  CLEANUP_INTERVAL: 10 * 1000,
} as const;
